// lib/api/index.ts

// Re-export core functionality
export { apiRequest } from "./core";

// Re-export all API modules
export { clientApi } from "./client/client";
export { guildApi } from "./guild/guild";
export { botStatusApi } from "./botstatus/botstatus";
export { botConfigApi } from "./botconfig/botconfig";
export { afkApi } from "./afk/afk";
export { lastfmApi } from "./lastfm/lastfm";
export { chatApi } from "./chat/chat";
export { confessionsApi } from "./confessions/confessions";
export { birthdayApi } from "./birthday/birthday";
export { administrationApi } from "./administration/administration";
export { chatTriggersApi } from "./chattriggers/chattriggers";
export { ownershipApi } from "./ownership/ownership";
export { reviewsApi } from "./reviews/reviews";
export { instanceManagementApi } from "./instancemanagement/instancemanagement";
export { moderationApi } from "./moderation/moderation";
export { systemInfoApi } from "./systeminfo/systeminfo";
export { performanceApi } from "./performance/performance";
export { permissionsApi } from "./permissions/permissions";
export { inviteTrackingApi } from "./invitetracking/invitetracking";
export { joinLeaveApi } from "./joinleave/joinleave";
export { roleGreetApi } from "./rolegreet/rolegreet";
export { roleStatesApi } from "./rolestates/rolestates";
export { starboardApi } from "./starboard/starboard";
export { multiGreetApi } from "./multigreet/multigreet";
export { giveawaysApi } from "./giveaways/giveaways";
export { feedsApi } from "./feeds/feeds";
export { todoApi } from "./todo/todo";
export { votesApi } from "./votes/votes";
export { highlightsApi } from "./highlights/highlights";
export { statusRolesApi } from "./statusroles/statusroles";
export { streamNotificationsApi } from "./streamnotifications/streamnotifications";
export { reputationApi } from "./reputation/reputation";
export { customVoiceApi } from "./customvoice/customvoice";
export { messageCountApi } from "./messagecount/messagecount";
export { filterApi } from "./filter/filter";
export { loggingApi } from "./logging/logging";
export { protectionApi } from "./protection/protection";
export { suggestionsApi } from "./suggestions/suggestions";
export { xpApi } from "./xp/xp";
export { musicApi } from "./music/music";
export { patreonApi } from "./patreon/patreon";
export { twitchApi } from "./twitch/twitch";
export { repeatersApi } from "./repeaters/repeaters";
export { wizardApi } from "./wizard/wizard";
export { countingApi } from "./counting/counting";
export { currencyApi } from "./currency/currency";
export { meApi } from "./me/me";
export { pollApi } from "./poll/poll";
export { ticketApi } from "./ticket/ticket";
export { formsApi } from "./forms/forms";
export { minecraftApi } from "./minecraft/minecraft";
export { statChannelsApi } from "./statchannels/statchannels";
export { auditLogApi } from "./auditlog/auditlog";
export { embedsApi } from "./embeds/embeds";
export { dashboardAccessApi } from "./dashboardaccess/dashboardaccess";

// Re-export all models
export * from "./client/models";
export * from "./guild/models";
export * from "./botstatus/models";
export * from "./botconfig/models";
export * from "./afk/models";
export * from "./chat/models";
export * from "./confessions/models";
export * from "./birthday/models";
export * from "./administration/models";
export * from "./chattriggers/models";
export * from "./reviews/models";
export * from "./instancemanagement/models";
export * from "./moderation/models";
export * from "./systeminfo/models";
export * from "./performance/models";
// @ts-ignore
export * from "./permissions/models";
export * from "./invitetracking/models";
export * from "./joinleave/models";
export * from "./lastfm/models";
export * from "./rolegreet/models";
export * from "./rolestates/models";
export * from "./starboard/models";
export * from "./multigreet/models";
export * from "./giveaways/models";
export * from "./feeds/models";
export * from "./todo/models";
export * from "./votes/models";
export * from "./highlights/models";
export * from "./statusroles/models";
export * from "./streamnotifications/models";
export * from "./reputation/models";
export * from "./customvoice/models";
export * from "./messagecount/models";
export * from "./filter/models";
export * from "./logging/models";
export * from "./protection/models";
export * from "./suggestions/models";
export * from "./xp/models";
export * from "./music/models";
export * from "./patreon/models";
export * from "./twitch/models";
export * from "./repeaters/models";
export * from "./wizard/models";
export * from "./counting/models";
export * from "./currency/models";
export * from "./me/models";
export * from "./poll/models";
export * from "./ticket/models";
export * from "./forms/models";
export * from "./minecraft/models";
export * from "./statchannels/models";
export * from "./auditlog/models";
export * from "./embeds/models";
export * from "./dashboardaccess/models";
